### PR TITLE
Adding the option to create module without storyboard

### PR DESCRIPTION
**Pull request by djangdal**
This will add the support of creating modules without the storyboard.

It could be improved further with adding the storyboard and view controller name as associated values on the enum.

### CODE REVIEW

**Review by mayur-ios-dev — COMMENTED** [review]
I think there is a less complicated way to do this.

**Comment by mayur-ios-dev** [comment]
> I think there is a less complicated way to do this.

If you make a protocol called `Instantiable` with static method `instantiate`.  Inherit `StoryboardInstantiable` from `Instantiable` and extension of `StoryboardInstantiable` providing definition of `instantiate` to just call `instantiateFromStoryboard()` it will allow going from

```swift
StoryboardInstantiable & ViewControllerInitProtocol
```

to only `Instantiable`

**Comment by mayur-ios-dev** [comment]
That will also save a lot of other code about case matching.

**Comment by djangdal** [comment]
> I think there is a less complicated way to do this.


> > I think there is a less complicated way to do this.
> 
> If you make a protocol called `Instantiable` with static method `instantiate`. Inherit `StoryboardInstantiable` from `Instantiable` and extension of `StoryboardInstantiable` providing definition of `instantiate` to just call `instantiateFromStoryboard()` it will allow going from
> 
> ```swift
> StoryboardInstantiable & ViewControllerInitProtocol
> ```
> 
> to only `Instantiable`

But then we have to specify on each module if they are storyboard instantiable, or just instantiable. And I wanted to avoid doing that big of a change right now

**Review by mayur-ios-dev — COMMENTED** [review]
Let's close this one then?

**Pull request closed without merging**
